# Generated by Django 3.2.12 on 2024-02-26 14:20

import django.contrib.auth.password_validation
import django.core.validators
from django.db import migrations, models
import facebook.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(validators=[facebook.models.custom_validators.validate_is_older_than_thirteen]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, validators=[facebook.models.custom_validators.validate_no_special_characters, django.core.validators.MaxLengthValidator(30)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(300), django.contrib.auth.password_validation.validate_password]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=40, validators=[facebook.models.custom_validators.validate_no_special_characters]),
        ),
    ]
