# Generated by Django 3.2.12 on 2024-02-27 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_auto_20240226_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='images/user.png', upload_to='images/', validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
    ]
