# Generated by Django 3.2.12 on 2024-02-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/home/venkatalakshmi/FacebookFinal/facebook/static/images/user.png', null=True, upload_to='images/'),
        ),
    ]
