# Generated by Django 3.2.12 on 2024-02-28 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('friendship_id', models.AutoField(primary_key=True, serialize=False)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_friendships', to='facebook.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_friendships', to='facebook.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
