# Generated by Django 3.2.12 on 2024-02-28 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0006_auto_20240228_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to='facebook.User')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facebook.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
