# Generated by Django 3.2.12 on 2024-02-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0009_auto_20240228_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='info_about_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
