# Generated by Django 3.2.12 on 2024-02-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0010_alter_posts_info_about_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
