# Generated by Django 3.2.12 on 2024-03-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0013_friendrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_picture',
            field=models.ImageField(blank=True, default='/home/venkatalakshmi/FacebookFinal/facebook/static/images/white.jpg', null=True, upload_to='images/'),
        ),
    ]
