# Generated by Django 3.2.12 on 2024-03-03 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0014_user_cover_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked_time',
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_text',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='from_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.user'),
        ),
    ]
