# Generated by Django 3.2.12 on 2024-03-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0015_auto_20240303_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_file',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
