# Generated by Django 3.2.12 on 2024-03-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0016_alter_post_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_file',
            field=models.FileField(upload_to='images/'),
        ),
    ]
